# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

include Math

def pentagonal?(number)
  check = ((sqrt((24 * number) + 1)) + 1) / 6
  return (check % 1).zero?
end

pentagonals = (1..3000).map { |n| n*(3*n-1)/2 }
pentagonals_combos = pentagonals.combination(2)

answer = 0
pentagonals_combos.each do |pk, pj|
  d = (pk - pj).abs
  next unless pentagonal?(d)
  answer = d if pentagonal?(pj + pk)
end

puts answer
