# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
# Find the next triangle number that is also pentagonal and hexagonal.

include Math

def pentagonal?(number)
  check = ((sqrt((24 * number) + 1)) + 1) / 6
  (check % 1).zero?
end

def hexagonal?(number)
  check = ((sqrt((8 * number) + 1)) + 1) / 4
  (check % 1).zero?
end

def get_triangle(number)
  (number * (number + 1)) / 2
end

number = 286

loop do
  triangle = get_triangle(number)
  break if pentagonal?(triangle) && hexagonal?(triangle)
  number = number.next
end

puts "The next triangle number after 40755 that's also pentagonal and hexagonal is #{get_triangle(number)}"
